[build]
  # Commande de build — installation + compilation
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  
  # Dossier de sortie du build
  publish = "dist/public"
  
  # Fonctions serverless Netlify
  functions = "netlify/functions"

[build.environment]
  # Version de Node.js
  NODE_VERSION = "22.13.0"

  # Environnement de build
  NODE_ENV = "production"

  # Empêche l'échec du build si le lockfile n'est pas strictement à jour
  PNPM_FLAGS = "--no-frozen-lockfile"

# Redirection API vers fonctions serverless
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

# Redirection SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache longue durée pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des fonctions serverless
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mysql2"]
  included_files = ["drizzle/**"]
