[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "22.13.0"   # OK pour Vite 7
  NODE_ENV     = "production"
  PNPM_FLAGS   = "--no-frozen-lockfile"

# tRPC -> Function api (avant le fallback SPA)
[[redirects]]
  from = "/trpc/*"
  to   = "/.netlify/functions/api/trpc/:splat"
  status = 200

# (optionnel) tes REST endpoints s'il y en a
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/server/:splat"
  status = 200

# Fallback SPA en dernier
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "mysql2"]
  included_files = ["drizzle/**"]
