# =========================
# Netlify configuration
# =========================

[build]
  # Netlify installe déjà les deps, mais on force PNPM + build
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  # Dossier de sortie du bundler (Vite/React = "dist")
  publish = "dist"

[build.environment]
  # Choisis un LTS largement supporté par Netlify Functions
  NODE_VERSION = "20.18.0"
  NODE_ENV     = "production"
  PNPM_FLAGS   = "--no-frozen-lockfile"

# IMPORTANT : redirections spécifiques AVANT le fallback SPA
# 1) tRPC → Function "api" (awsLambdaRequestHandler) 
[[redirects]]
  from = "/trpc/*"
  to   = "/.netlify/functions/api/trpc/:splat"
  status = 200

# 2) (optionnel) API REST → Function "api" si tu en as besoin
[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200

# 3) Fallback SPA (doit rester EN DERNIER)
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache longue durée pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Fonctions serverless
[functions]
  directory = "netlify/functions"    # <-- dossier des Functions
  node_bundler = "esbuild"
  # Garde ces modules externes si tu en dépends (sinon tu peux les retirer)
  external_node_modules = ["express", "mysql2"]
  included_files = ["drizzle/**"]
